# Generated by Django 3.2.9 on 2021-12-05 12:27

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('seats', models.IntegerField(default=1)),
                ('time', models.IntegerField(choices=[(0, '11.00/12.00'), (1, '12.00/13.00'), (2, '13.00/14.00'), (3, '14.00/15.00'), (4, '18.00/19.00'), (5, '19.00/20.00'), (6, '20.00/21.00'), (7, '21.00/22.00')], default=0)),
            ],
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['seats', 'day', 'month', 'year', 'time'], name='booking_res_seats_507c35_idx'),
        ),
    ]
