# Generated by Django 3.2.9 on 2022-01-03 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_size', models.PositiveIntegerField()),
                ('date', models.DateField(null=True)),
                ('time', models.CharField(choices=[('1', '10.00-11.00'), ('2', '11.00-12.00'), ('3', '12.00-13.00'), ('4', '13.00-14.00'), ('5', '19.00-20.00'), ('6', '20.00-21.00'), ('7', '21.00-22.00'), ('8', '22.00-23.00')], max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
