# Generated by Django 3.2.9 on 2021-12-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('1', '10.00-11.00'), ('2', '11.00-12.00')], max_length=100),
        ),
    ]
