# Generated by Django 3.2.9 on 2022-01-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('1', '10.00-11.00'), ('2', '11.00-12.00'), ('3', '12.00-13.00'), ('4', '13.00-14.00'), ('5', '19.00-20.00'), ('6', '20.00-21.00'), ('7', '21.00-22.00'), ('8', '22.00-23.00')], max_length=100),
        ),
    ]
